// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWL9189juK2xiXui54UocHaq0W4vdNgs',
    appId: '1:887922191929:web:6af6b394fc9b55afc527e8',
    messagingSenderId: '887922191929',
    projectId: 'tmdt-2536c',
    authDomain: 'tmdt-2536c.firebaseapp.com',
    storageBucket: 'tmdt-2536c.firebasestorage.app',
    measurementId: 'G-9JKGYPQ5SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx18fGMuQzzpOghJxzcbA-0SxiJBQKEpQ',
    appId: '1:887922191929:android:57f64b4431e90211c527e8',
    messagingSenderId: '887922191929',
    projectId: 'tmdt-2536c',
    storageBucket: 'tmdt-2536c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GUf6mdOkHQ0jC-PtCodH4LiN89eZGmU',
    appId: '1:887922191929:ios:b57a676a794fe62fc527e8',
    messagingSenderId: '887922191929',
    projectId: 'tmdt-2536c',
    storageBucket: 'tmdt-2536c.firebasestorage.app',
    iosClientId: '887922191929-fm6t08qh8mvflenndhvblbt8mtgc97c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminTmdt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3GUf6mdOkHQ0jC-PtCodH4LiN89eZGmU',
    appId: '1:887922191929:ios:b57a676a794fe62fc527e8',
    messagingSenderId: '887922191929',
    projectId: 'tmdt-2536c',
    storageBucket: 'tmdt-2536c.firebasestorage.app',
    iosClientId: '887922191929-fm6t08qh8mvflenndhvblbt8mtgc97c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminTmdt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWL9189juK2xiXui54UocHaq0W4vdNgs',
    appId: '1:887922191929:web:c59f3a3270d7e076c527e8',
    messagingSenderId: '887922191929',
    projectId: 'tmdt-2536c',
    authDomain: 'tmdt-2536c.firebaseapp.com',
    storageBucket: 'tmdt-2536c.firebasestorage.app',
    measurementId: 'G-4ZX2439GVV',
  );
}
